<Project Sdk="Microsoft.NET.Sdk">

  <!--
    BCSTool.csproj tells the .NET SDK how to build the application.

    Important settings:
      OutputType=WinExe       => Windows GUI application
      TargetFramework        => .NET 10 + Windows APIs
      UseWPF=true            => enable Windows Presentation Foundation
      Nullable=enable        => compiler helps catch null-reference bugs
      ImplicitUsings=enable  => common namespaces are automatically imported
  -->
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>BCS Tool</AssemblyName>
    <Title>BCS Tool</Title>
    <Product>BCS Tool</Product>
    <Description>Bannerlord Coop Server management tool</Description>
    <RootNamespace>BCSTool</RootNamespace>
	<Version>0.3.0</Version>
	<PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>
</Project>
